services:
  postgres:
    image: postgres:17
    container_name: gamehuclearb_db
    environment:
      POSTGRES_DB: gamehub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
